const MEDIA_CATEGORIES = ["SRC Activities", "Events", "Awards", "Sports", "Academic", "Entertainment", "Leadership", "Community Service", "Other"];
const MEDIA_STATUSES = ["draft", "published", "archived"];
const SETTINGS_KEYS = ["srcName", "institution", "officialEmail", "officialPhone", "instagram", "tiktok", "facebook", "activeTerm", "footerText"];

function httpError(message, status = 400) { const error = new Error(message); error.status = status; return error; }
function text(value, name, { required = false, min = 0, max = 2000 } = {}) { const clean = String(value ?? "").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, "").trim(); if (required && clean.length < min) throw httpError(`${name} is required.`); if (clean.length > max) throw httpError(`${name} is too long.`); if (/<\/?[a-z][\s\S]*>/i.test(clean)) throw httpError(`${name} must contain plain text only.`); return clean; }
function choice(value, allowed, name, fallback) { const clean = String(value ?? fallback ?? ""); if (!allowed.includes(clean)) throw httpError(`Invalid ${name}.`); return clean; }
function bool(value) { return value === true || value === 1 || value === "1" || value === "true"; }
function id(value) { const parsed = Number(value); if (!Number.isInteger(parsed) || parsed < 1) throw httpError("Invalid record ID."); return parsed; }
function date(value, name, optional = false) { const clean = String(value || ""); if (!clean && optional) return null; const parsed = new Date(`${clean}T00:00:00Z`); if (!/^\d{4}-\d{2}-\d{2}$/.test(clean) || Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0,10) !== clean) throw httpError(`${name} is invalid.`); return clean; }
function email(value) { const clean = text(value, "Email", { max: 254 }); if (clean && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean)) throw httpError("Email is invalid."); return clean || null; }
function phone(value) { const clean = text(value, "Phone", { max: 24 }); if (clean && !/^\+?[0-9 ()-]{7,24}$/.test(clean)) throw httpError("Phone is invalid."); return clean || null; }
function safeLink(value, name) { const clean = text(value, name, { max: 500 }); if (!clean) return null; let parsed; try { parsed = new URL(clean); } catch { throw httpError(`${name} is invalid.`); } if (parsed.protocol !== "https:") throw httpError(`${name} must use HTTPS.`); return clean; }
function slugify(value) { return String(value).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90) || "record"; }
function like(value) { return `%${String(value || "").slice(0,100)}%`; }
function ensureAuditColumns(db) { const existing = new Set(db.prepare("PRAGMA table_info(audit_log)").all().map(row => row.name)); for (const [column,type] of [["admin_role","TEXT"],["resource_type","TEXT"],["resource_id","TEXT"],["summary","TEXT"]]) if (!existing.has(column)) db.exec(`ALTER TABLE audit_log ADD COLUMN ${column} ${type}`); }

function createContentRepository(db) {
  ensureAuditColumns(db);
  db.exec(`
    CREATE TABLE IF NOT EXISTS media_albums (
      id INTEGER PRIMARY KEY, title TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, description TEXT NOT NULL,
      category TEXT NOT NULL, album_date TEXT NOT NULL, cover_token TEXT, featured INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'draft', created_by TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS media_items (
      id INTEGER PRIMARY KEY, album_id INTEGER NOT NULL REFERENCES media_albums(id) ON DELETE CASCADE,
      image_token TEXT NOT NULL, thumbnail_token TEXT, caption TEXT, alt_text TEXT NOT NULL,
      display_order INTEGER NOT NULL DEFAULT 0, photographer TEXT, featured INTEGER NOT NULL DEFAULT 0,
      uploaded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS src_executives (
      id INTEGER PRIMARY KEY, slug TEXT NOT NULL UNIQUE, full_name TEXT NOT NULL, position TEXT NOT NULL,
      photo_token TEXT, short_bio TEXT NOT NULL, biography TEXT NOT NULL, responsibilities TEXT NOT NULL,
      email TEXT, phone TEXT, social_url TEXT, programme TEXT, term TEXT NOT NULL, display_order INTEGER NOT NULL DEFAULT 0,
      active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS site_settings (
      setting_key TEXT PRIMARY KEY, setting_value TEXT NOT NULL, updated_by TEXT, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE INDEX IF NOT EXISTS idx_media_public ON media_albums(status, featured DESC, album_date DESC);
    CREATE INDEX IF NOT EXISTS idx_media_items_album ON media_items(album_id, display_order, id);
    CREATE INDEX IF NOT EXISTS idx_executives_public ON src_executives(active, term, display_order, id);
    CREATE INDEX IF NOT EXISTS idx_audit_recent ON audit_log(created_at DESC, id DESC);
    PRAGMA optimize;
  `);
  const settingDefaults = { srcName: "Your SRC Name", institution: "Your Institution / Campus", officialEmail: "official-email@example.edu", officialPhone: "+233 XX XXX XXXX", instagram: "", tiktok: "", facebook: "", activeTerm: "", footerText: "Built for the student community." };
  const insertSetting = db.prepare("INSERT OR IGNORE INTO site_settings(setting_key,setting_value) VALUES(?,?)"); Object.entries(settingDefaults).forEach(entry => insertSetting.run(...entry));
  function uniqueSlug(table, value, ignore = null) { const base = slugify(value); let slug = base; let n = 2; const query = db.prepare(`SELECT id FROM ${table} WHERE slug=?`); while (true) { const row = query.get(slug); if (!row || row.id === ignore) return slug; slug = `${base}-${n++}`; } }
  function mediaUrl(token) { return token ? `/api/content/files/${token}` : null; }
  function mapItem(row) { return row ? { id: row.id, imageUrl: mediaUrl(row.image_token), thumbnailUrl: mediaUrl(row.thumbnail_token || row.image_token), caption: row.caption, altText: row.alt_text, displayOrder: row.display_order, photographer: row.photographer, featured: Boolean(row.featured), uploadedAt: row.uploaded_at } : null; }
  function mapAlbum(row, includeItems = false) { if (!row) return null; const album = { id: row.id, title: row.title, slug: row.slug, description: row.description, category: row.category, albumDate: row.album_date, coverUrl: mediaUrl(row.cover_token), featured: Boolean(row.featured), status: row.status, createdBy: row.created_by, createdAt: row.created_at, updatedAt: row.updated_at, photoCount: Number(row.photo_count || 0) }; if (includeItems) album.items = db.prepare("SELECT * FROM media_items WHERE album_id=? ORDER BY display_order,id").all(row.id).map(mapItem); return album; }
  function listAlbumsPublic(filters = {}) { const clauses = ["a.status='published'"], params=[]; if (filters.category) { clauses.push("a.category=?"); params.push(choice(filters.category, MEDIA_CATEGORIES, "category")); } if (filters.q) { clauses.push("(a.title LIKE ? OR a.description LIKE ?)"); params.push(like(filters.q),like(filters.q)); } return db.prepare(`SELECT a.*,COUNT(i.id) photo_count FROM media_albums a LEFT JOIN media_items i ON i.album_id=a.id WHERE ${clauses.join(" AND ")} GROUP BY a.id ORDER BY a.featured DESC,a.album_date DESC LIMIT 100`).all(...params).map(mapAlbum); }
  function featuredAlbums() { return db.prepare("SELECT a.*,COUNT(i.id) photo_count FROM media_albums a LEFT JOIN media_items i ON i.album_id=a.id WHERE a.status='published' GROUP BY a.id ORDER BY a.featured DESC,a.album_date DESC LIMIT 3").all().map(mapAlbum); }
  function getAlbumPublic(slug) { const row = db.prepare("SELECT a.*,COUNT(i.id) photo_count FROM media_albums a LEFT JOIN media_items i ON i.album_id=a.id WHERE a.slug=? AND a.status='published' GROUP BY a.id").get(String(slug||"")); return mapAlbum(row,true); }
  function listAlbumsAdmin(filters={}) { const clauses=["1=1"],params=[]; if(filters.status){clauses.push("a.status=?");params.push(choice(filters.status,MEDIA_STATUSES,"status"));} if(filters.category){clauses.push("a.category=?");params.push(choice(filters.category,MEDIA_CATEGORIES,"category"));} if(filters.q){clauses.push("a.title LIKE ?");params.push(like(filters.q));} return db.prepare(`SELECT a.*,COUNT(i.id) photo_count FROM media_albums a LEFT JOIN media_items i ON i.album_id=a.id WHERE ${clauses.join(" AND ")} GROUP BY a.id ORDER BY a.updated_at DESC LIMIT 200`).all(...params).map(mapAlbum); }
  function getAlbumAdmin(albumId) { return mapAlbum(db.prepare("SELECT a.*,COUNT(i.id) photo_count FROM media_albums a LEFT JOIN media_items i ON i.album_id=a.id WHERE a.id=? GROUP BY a.id").get(id(albumId)),true); }
  function albumInput(input, current = {}) { return { title:text(input.title??current.title,"Title",{required:true,min:3,max:160}),description:text(input.description??current.description,"Description",{required:true,min:10,max:5000}),category:choice(input.category,MEDIA_CATEGORIES,"category",current.category),albumDate:date(input.albumDate??current.albumDate,"Album date"),featured:bool(input.featured),status:choice(input.status,MEDIA_STATUSES,"status",current.status||"draft") }; }
  function createAlbum(input, role, cover) { const v=albumInput(input); const slug=uniqueSlug("media_albums",v.title); const result=db.prepare("INSERT INTO media_albums(title,slug,description,category,album_date,cover_token,featured,status,created_by) VALUES(?,?,?,?,?,?,?,?,?)").run(v.title,slug,v.description,v.category,v.albumDate,cover?.token||null,v.featured?1:0,v.status,role); return getAlbumAdmin(Number(result.lastInsertRowid)); }
  function updateAlbum(albumId,input,cover) { const current=getAlbumAdmin(albumId); if(!current)throw httpError("Album not found.",404); const v=albumInput(input,current); db.prepare("UPDATE media_albums SET title=?,description=?,category=?,album_date=?,cover_token=COALESCE(?,cover_token),featured=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(v.title,v.description,v.category,v.albumDate,cover?.token||null,v.featured?1:0,v.status,id(albumId)); return getAlbumAdmin(albumId); }
  function deleteAlbum(albumId){const current=getAlbumAdmin(albumId);if(!current)throw httpError("Album not found.",404);db.prepare("DELETE FROM media_albums WHERE id=?").run(id(albumId));return current;}
  function addItems(albumId,items){if(!getAlbumAdmin(albumId))throw httpError("Album not found.",404);const next=Number(db.prepare("SELECT COALESCE(MAX(display_order),-1)+1 value FROM media_items WHERE album_id=?").get(id(albumId)).value);const add=db.prepare("INSERT INTO media_items(album_id,image_token,caption,alt_text,display_order,photographer,featured) VALUES(?,?,?,?,?,?,?)");items.forEach((item,index)=>add.run(id(albumId),item.file.token,text(item.caption,"Caption",{max:500})||null,text(item.altText,"Alternative text",{required:true,min:3,max:300}),next+index,text(item.photographer,"Photographer",{max:120})||null,bool(item.featured)?1:0));return getAlbumAdmin(albumId);}
  function updateItem(itemId,input){const row=db.prepare("SELECT * FROM media_items WHERE id=?").get(id(itemId));if(!row)throw httpError("Photo not found.",404);db.prepare("UPDATE media_items SET caption=?,alt_text=?,display_order=?,photographer=?,featured=? WHERE id=?").run(text(input.caption??row.caption,"Caption",{max:500})||null,text(input.altText??row.alt_text,"Alternative text",{required:true,min:3,max:300}),Math.max(0,Math.min(10000,Number(input.displayOrder??row.display_order)||0)),text(input.photographer??row.photographer,"Photographer",{max:120})||null,bool(input.featured)?1:0,id(itemId));return mapItem(db.prepare("SELECT * FROM media_items WHERE id=?").get(id(itemId)));}
  function deleteItem(itemId){const row=db.prepare("SELECT * FROM media_items WHERE id=?").get(id(itemId));if(!row)throw httpError("Photo not found.",404);db.prepare("DELETE FROM media_items WHERE id=?").run(id(itemId));return row;}
  function mapExecutive(row,admin=false){if(!row)return null;const value={id:row.id,slug:row.slug,fullName:row.full_name,position:row.position,photoUrl:mediaUrl(row.photo_token),shortBio:row.short_bio,biography:row.biography,responsibilities:row.responsibilities,email:row.email,phone:row.phone,socialUrl:row.social_url,programme:row.programme,term:row.term,displayOrder:row.display_order,active:Boolean(row.active),createdAt:row.created_at,updatedAt:row.updated_at};if(admin)value.photoToken=row.photo_token;return value;}
  function listExecutivesPublic(term){const activeTerm=term||settings().activeTerm;const rows=activeTerm?db.prepare("SELECT * FROM src_executives WHERE active=1 AND term=? ORDER BY display_order,id").all(activeTerm):db.prepare("SELECT * FROM src_executives WHERE active=1 ORDER BY term DESC,display_order,id").all();return rows.map(mapExecutive);}
  function getExecutivePublic(slug){return mapExecutive(db.prepare("SELECT * FROM src_executives WHERE slug=? AND active=1").get(String(slug||"")));}
  function listExecutivesAdmin(filters={}){const clauses=["1=1"],params=[];if(filters.term){clauses.push("term=?");params.push(text(filters.term,"Term",{max:20}));}if(filters.q){clauses.push("(full_name LIKE ? OR position LIKE ?)");params.push(like(filters.q),like(filters.q));}return db.prepare(`SELECT * FROM src_executives WHERE ${clauses.join(" AND ")} ORDER BY term DESC,display_order,id LIMIT 200`).all(...params).map(row=>mapExecutive(row,true));}
  function getExecutiveAdmin(executiveId){return mapExecutive(db.prepare("SELECT * FROM src_executives WHERE id=?").get(id(executiveId)),true);}
  function executiveInput(input,current={}){return{fullName:text(input.fullName??current.fullName,"Full name",{required:true,min:2,max:140}),position:text(input.position??current.position,"Position",{required:true,min:2,max:140}),shortBio:text(input.shortBio??current.shortBio,"Short biography",{required:true,min:10,max:500}),biography:text(input.biography??current.biography,"Biography",{required:true,min:20,max:5000}),responsibilities:text(input.responsibilities??current.responsibilities,"Responsibilities",{required:true,min:10,max:3000}),email:email(input.email??current.email),phone:phone(input.phone??current.phone),socialUrl:safeLink(input.socialUrl??current.socialUrl,"Social link"),programme:text(input.programme??current.programme,"Programme",{max:160})||null,term:text(input.term??current.term,"Term",{required:true,min:4,max:20}),displayOrder:Math.max(0,Math.min(10000,Number(input.displayOrder??current.displayOrder)||0)),active:bool(input.active)}}
  function createExecutive(input,photo){const v=executiveInput(input);const slug=uniqueSlug("src_executives",v.fullName);const result=db.prepare("INSERT INTO src_executives(slug,full_name,position,photo_token,short_bio,biography,responsibilities,email,phone,social_url,programme,term,display_order,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(slug,v.fullName,v.position,photo?.token||null,v.shortBio,v.biography,v.responsibilities,v.email,v.phone,v.socialUrl,v.programme,v.term,v.displayOrder,v.active?1:0);return getExecutiveAdmin(Number(result.lastInsertRowid));}
  function updateExecutive(executiveId,input,photo){const current=getExecutiveAdmin(executiveId);if(!current)throw httpError("Executive not found.",404);const v=executiveInput(input,current);db.prepare("UPDATE src_executives SET full_name=?,position=?,photo_token=COALESCE(?,photo_token),short_bio=?,biography=?,responsibilities=?,email=?,phone=?,social_url=?,programme=?,term=?,display_order=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(v.fullName,v.position,photo?.token||null,v.shortBio,v.biography,v.responsibilities,v.email,v.phone,v.socialUrl,v.programme,v.term,v.displayOrder,v.active?1:0,id(executiveId));return getExecutiveAdmin(executiveId);}
  function deleteExecutive(executiveId){const current=getExecutiveAdmin(executiveId);if(!current)throw httpError("Executive not found.",404);db.prepare("DELETE FROM src_executives WHERE id=?").run(id(executiveId));return current;}
  function settings(){return Object.fromEntries(db.prepare("SELECT setting_key,setting_value FROM site_settings").all().map(row=>[row.setting_key,row.setting_value]));}
  function updateSettings(input,role){const update=db.prepare("UPDATE site_settings SET setting_value=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE setting_key=?");for(const key of SETTINGS_KEYS)if(Object.hasOwn(input,key)){const value=text(input[key],key,{max:500});if(["instagram","tiktok","facebook"].includes(key)&&value)safeLink(value,key);if(key==="officialEmail"&&value)email(value);update.run(value,role,key);}return settings();}
  function audit(admin,action,resourceType,resourceId,summary){db.prepare("INSERT INTO audit_log(action,admin_role,resource_type,resource_id,summary) VALUES(?,?,?,?,?)").run(text(action,"Action",{required:true,max:100}),admin?.role||"system",text(resourceType,"Resource",{max:80})||null,String(resourceId??"").slice(0,80)||null,text(summary,"Summary",{max:300})||null);}
  function recentAudit(limit=30){return db.prepare("SELECT id,action,admin_role adminRole,resource_type resourceType,resource_id resourceId,summary,created_at createdAt FROM audit_log ORDER BY id DESC LIMIT ?").all(Math.max(1,Math.min(100,Number(limit)||30)));}
  function dashboard(){const scalar=sql=>Number(db.prepare(sql).get().value);return{publishedAlbums:scalar("SELECT COUNT(*) value FROM media_albums WHERE status='published'"),draftAlbums:scalar("SELECT COUNT(*) value FROM media_albums WHERE status='draft'"),mediaItems:scalar("SELECT COUNT(*) value FROM media_items"),activeExecutives:scalar("SELECT COUNT(*) value FROM src_executives WHERE active=1")};}
  function publicFile(token){if(!/^[a-f0-9]{32}\.[a-z0-9]{2,5}$/.test(String(token||"")))return null;const media=db.prepare("SELECT 1 FROM media_albums a LEFT JOIN media_items i ON i.album_id=a.id WHERE a.status='published' AND (a.cover_token=? OR i.image_token=? OR i.thumbnail_token=?) LIMIT 1").get(token,token,token);const executive=db.prepare("SELECT 1 FROM src_executives WHERE active=1 AND photo_token=?").get(token);return media||executive?token:null;}
  return{categories:MEDIA_CATEGORIES,statuses:MEDIA_STATUSES,listAlbumsPublic,featuredAlbums,getAlbumPublic,listAlbumsAdmin,getAlbumAdmin,createAlbum,updateAlbum,deleteAlbum,addItems,updateItem,deleteItem,listExecutivesPublic,getExecutivePublic,listExecutivesAdmin,getExecutiveAdmin,createExecutive,updateExecutive,deleteExecutive,settings,updateSettings,audit,recentAudit,dashboard,publicFile};
}

module.exports = { createContentRepository };
