const crypto = require("node:crypto");

const PHASE_STATUSES = ["draft", "scheduled", "open", "paused", "closed", "archived"];
const SUBMISSION_STATUSES = ["pending_review", "valid", "invalid", "flagged"];
const NOMINEE_STATUSES = ["under_review", "eligible", "ineligible", "shortlisted", "consent_pending", "verified", "ready_for_publication", "withdrawn"];
const PUBLIC_POSITIONS = ["after_hero", "after_pulse", "after_quick_access"];
const DEFAULT_RULES = `Nominations are free.
Nominations are not votes.
A verified student may nominate one candidate per category.
The same candidate may be nominated by different students.
Duplicate submissions from the same nominator in the same category will not increase the count.
False, abusive or unverifiable submissions may be rejected.
Nomination totals do not automatically guarantee shortlisting unless the published rules state otherwise.
Eligibility requirements still apply.
Nominee identities remain private during the open-nomination period.
Shortlisted nominees will be contacted for verification and consent before publication.
Phone numbers and Student IDs will never be displayed publicly.
Public voting will open only after the official nominees are announced.
Special Recognition is selected by the committee and is not open to public nominations.`;

const GROUPS = [
  { slug: "level-300", name: "Level 300 Awards", order: 1 },
  { slug: "level-350", name: "Level 350 Awards", order: 2 },
  { slug: "general", name: "General Awards", order: 3 }
];
const CATEGORY_NAMES = {
  "level-300": ["Level 300 Student Personality of the Year", "Level 300 Most Popular Student of the Year", "Level 300 Most Influential Student of the Year", "Level 300 Best Course Rep of the Year", "Level 300 Most Fashionable Male", "Level 300 Most Fashionable Female", "Level 300 Most Supportive Student of the Year"],
  "level-350": ["Level 350 Student Personality of the Year", "Level 350 Most Popular Student of the Year", "Level 350 Most Influential Student of the Year", "Level 350 Best Course Rep of the Year", "Level 350 Most Fashionable Male", "Level 350 Most Fashionable Female", "Level 350 Most Supportive Student of the Year"],
  general: ["Campus Icon of the Year", "SRC Personality of the Year", "Student Entrepreneur of the Year", "Best Friends of the Year", "Most Photogenic Student of the Year", "Man of Our Time", "Woman of Our Time", "Digital Content & Social Media Personality of the Year", "Sports Personality of the Year", "Most Disciplined Student of the Year", "Student Humanitarian of the Year", "Best Class of the Year", "Special Recognition Award", "Outstanding Student Leader of the Year"]
};
const CATEGORY_DESCRIPTIONS = Object.freeze({
  "Level 300 Student Personality of the Year": "Recognises a well-rounded Level 300 student known for strong character, confidence and positive engagement with others.",
  "Level 300 Most Popular Student of the Year": "Celebrates a Level 300 student who is widely known and genuinely appreciated for respectful connections across the student community.",
  "Level 300 Most Influential Student of the Year": "Honours a Level 300 student whose ideas and actions inspire peers, shape participation or create positive change.",
  "Level 300 Best Course Rep of the Year": "Recognises a Level 300 course representative who communicates reliably, advocates responsibly and keeps the class organised and informed.",
  "Level 300 Most Fashionable Male": "Celebrates a Level 300 male student with consistent personal style, creativity and confident, appropriate presentation.",
  "Level 300 Most Fashionable Female": "Celebrates a Level 300 female student with consistent personal style, creativity and confident, appropriate presentation.",
  "Level 300 Most Supportive Student of the Year": "Honours a dependable Level 300 student who regularly offers encouragement, practical help and genuine support to peers.",
  "Level 350 Student Personality of the Year": "Recognises a well-rounded Level 350 student known for strong character, confidence and positive engagement with others.",
  "Level 350 Most Popular Student of the Year": "Celebrates a Level 350 student who is widely known and genuinely appreciated for respectful connections across the student community.",
  "Level 350 Most Influential Student of the Year": "Honours a Level 350 student whose ideas and actions inspire peers, shape participation or create positive change.",
  "Level 350 Best Course Rep of the Year": "Recognises a Level 350 course representative who communicates reliably, advocates responsibly and keeps the class organised and informed.",
  "Level 350 Most Fashionable Male": "Celebrates a Level 350 male student with consistent personal style, creativity and confident, appropriate presentation.",
  "Level 350 Most Fashionable Female": "Celebrates a Level 350 female student with consistent personal style, creativity and confident, appropriate presentation.",
  "Level 350 Most Supportive Student of the Year": "Honours a dependable Level 350 student who regularly offers encouragement, practical help and genuine support to peers.",
  "Campus Icon of the Year": "Celebrates a highly visible and widely recognised student whose positive influence has made them a defining presence across campus.",
  "SRC Personality of the Year": "Recognises an SRC-associated person known for accessibility, service, good conduct and positive engagement with students.",
  "Student Entrepreneur of the Year": "Honours a student who demonstrates initiative, innovation and reliable business impact while serving the campus community.",
  "Best Friends of the Year": "Celebrates two students whose trust, mutual support and positive friendship set a strong example for the campus community.",
  "Most Photogenic Student of the Year": "Recognises a student whose confidence, natural camera presence and expressive style consistently stand out in photographs.",
  "Man of Our Time": "Honours a male student whose character, achievement and positive influence reflect an outstanding example to others.",
  "Woman of Our Time": "Honours a female student whose character, achievement and positive influence reflect an outstanding example to others.",
  "Digital Content & Social Media Personality of the Year": "Celebrates a student who creates responsible, original and engaging digital content that connects with the campus community.",
  "Sports Personality of the Year": "Recognises a student who demonstrates sporting excellence, commitment, teamwork and good sportsmanship.",
  "Most Disciplined Student of the Year": "Honours a student who consistently demonstrates integrity, respect, responsibility and exemplary conduct.",
  "Student Humanitarian of the Year": "Recognises a compassionate student whose voluntary service and practical support have improved the wellbeing of others.",
  "Best Class of the Year": "Celebrates a class distinguished by unity, academic commitment, active participation and positive contribution to campus life.",
  "Special Recognition Award": "Honours an exceptional contribution or achievement that deserves recognition beyond the standard award categories.",
  "Outstanding Student Leader of the Year": "Recognises a student who demonstrates leadership, responsibility and initiative with a measurable contribution to students or campus life."
});

function httpError(message, status = 400) { const error = new Error(message); error.status = status; return error; }
function clean(value, label, { required = false, min = 0, max = 1000 } = {}) {
  const text = String(value ?? "").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, "").trim();
  if (required && text.length < min) throw httpError(`${label} is required.`);
  if (text.length > max) throw httpError(`${label} must not exceed ${max} characters.`);
  if (/<\/?[a-z][\s\S]*>/i.test(text)) throw httpError(`${label} must contain plain text only.`);
  return text;
}
function bool(value) { return value === true || value === 1 || value === "1" || value === "true" || value === "on"; }
function numericId(value, label = "record") { const id = Number(value); if (!Number.isInteger(id) || id < 1) throw httpError(`Invalid ${label} ID.`); return id; }
function slugify(value) { return String(value).normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/&/g, " and ").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function normalizeName(value) { return clean(value, "Name", { required: true, min: 2, max: 140 }).normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9 ]/g, " ").replace(/\s+/g, " ").trim(); }
function normalizeStudentId(value) { const id = String(value ?? "").trim().replace(/\s+/g, "").toUpperCase(); if (!/^[A-Z0-9][A-Z0-9/_-]{3,39}$/.test(id)) throw httpError("Enter a valid Student ID."); return id; }
function normalizeGhanaPhone(value, required = true) {
  let digits = String(value ?? "").trim().replace(/[^0-9+]/g, "");
  if (!digits && !required) return null;
  if (digits.startsWith("+")) digits = digits.slice(1);
  if (/^0\d{9}$/.test(digits)) digits = `233${digits.slice(1)}`;
  if (!/^233\d{9}$/.test(digits) || /^2330+$/.test(digits)) throw httpError("Enter a valid Ghana phone number.");
  return `+${digits}`;
}
function timestamp(value, label, required = false) { const text = String(value ?? "").trim(); if (!text) { if (required) throw httpError(`${label} is required.`); return null; } if (!/(Z|[+-]\d{2}:\d{2})$/i.test(text)) throw httpError(`${label} must include a UTC offset.`); const parsed = new Date(text); if (Number.isNaN(parsed.getTime())) throw httpError(`${label} is invalid.`); return parsed.toISOString(); }
function nowIso(clock) { const value = clock(); return (value instanceof Date ? value : new Date(value)).toISOString(); }
function choice(value, allowed, label, fallback) { const result = String(value ?? fallback ?? ""); if (!allowed.includes(result)) throw httpError(`Invalid ${label}.`); return result; }
function csvCell(value) { let text = String(value ?? "").replace(/\r?\n/g, " "); if (/^[=+\-@]/.test(text)) text = `'${text}`; return `"${text.replace(/"/g, '""')}"`; }
function transaction(db, task) { db.exec("BEGIN IMMEDIATE"); try { const result = task(); db.exec("COMMIT"); return result; } catch (error) { try { db.exec("ROLLBACK"); } catch {} throw error; } }
function pairKey(first, second) { return [normalizeName(first), normalizeName(second)].sort().join("|"); }
function similarity(left, right) { const a = new Set(left.split(" ")), b = new Set(right.split(" ")); const shared = [...a].filter(item => b.has(item)).length; return shared / Math.max(a.size, b.size, 1); }

function createNominationRepository(db, options = {}) {
  const clock = options.clock || (() => new Date());
  db.exec(`
    CREATE TABLE IF NOT EXISTS nomination_award_groups (id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, sort_order INTEGER NOT NULL);
    CREATE TABLE IF NOT EXISTS nomination_categories (
      id INTEGER PRIMARY KEY AUTOINCREMENT, group_id INTEGER NOT NULL REFERENCES nomination_award_groups(id), slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL,
      description TEXT NOT NULL DEFAULT '', eligibility_instructions TEXT NOT NULL DEFAULT '', category_type TEXT NOT NULL DEFAULT 'individual' CHECK(category_type IN ('individual','pair','class')),
      active INTEGER NOT NULL DEFAULT 1, public_nominations INTEGER NOT NULL DEFAULT 1, max_finalists INTEGER NOT NULL DEFAULT 5 CHECK(max_finalists BETWEEN 1 AND 20), sort_order INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS nomination_phases (
      id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','scheduled','open','paused','closed','archived')),
      opens_at TEXT, closes_at TEXT, rules_snapshot TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE UNIQUE INDEX IF NOT EXISTS idx_nomination_live_phase ON nomination_phases((1)) WHERE status IN ('scheduled','open','paused');
    CREATE TABLE IF NOT EXISTS nomination_nominees (
      id INTEGER PRIMARY KEY AUTOINCREMENT, category_id INTEGER NOT NULL REFERENCES nomination_categories(id), nominee_type TEXT NOT NULL CHECK(nominee_type IN ('individual','pair','class')),
      display_name TEXT NOT NULL, normalized_key TEXT NOT NULL, level TEXT NOT NULL, programme TEXT NOT NULL, contact_phone TEXT,
      pair_first_name TEXT, pair_second_name TEXT, class_representative TEXT, status TEXT NOT NULL DEFAULT 'under_review' CHECK(status IN ('under_review','eligible','ineligible','shortlisted','consent_pending','verified','ready_for_publication','withdrawn')),
      internal_notes TEXT NOT NULL DEFAULT '', verified_name TEXT, verified_level TEXT, verified_programme TEXT, verified_phone TEXT, photo_token TEXT, public_bio TEXT, campaign_statement TEXT,
      contact_status TEXT NOT NULL DEFAULT 'not_contacted', consent_status TEXT NOT NULL DEFAULT 'not_requested', consent_received_at TEXT, ballot_order INTEGER, merged_into_id INTEGER REFERENCES nomination_nominees(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(category_id, normalized_key)
    );
    CREATE TABLE IF NOT EXISTS nomination_submissions (
      id INTEGER PRIMARY KEY AUTOINCREMENT, public_id TEXT NOT NULL UNIQUE, idempotency_key TEXT NOT NULL UNIQUE, phase_id INTEGER NOT NULL REFERENCES nomination_phases(id), category_id INTEGER NOT NULL REFERENCES nomination_categories(id), nominee_id INTEGER NOT NULL REFERENCES nomination_nominees(id),
      submitted_nominee_name TEXT NOT NULL, submitted_details TEXT NOT NULL DEFAULT '{}', nominee_phone TEXT, reason TEXT,
      nominator_name TEXT NOT NULL, nominator_student_id TEXT NOT NULL, nominator_phone TEXT NOT NULL, nominator_class TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'pending_review' CHECK(status IN ('pending_review','valid','invalid','flagged')), invalid_reason TEXT, review_notes TEXT NOT NULL DEFAULT '', rules_accepted_at TEXT NOT NULL,
      correlation_id TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(phase_id, category_id, nominator_student_id), UNIQUE(phase_id, category_id, nominator_phone)
    );
    CREATE INDEX IF NOT EXISTS idx_nomination_submissions_filters ON nomination_submissions(phase_id,category_id,status,created_at);
    CREATE INDEX IF NOT EXISTS idx_nomination_nominees_status ON nomination_nominees(category_id,status);
    CREATE TABLE IF NOT EXISTS nomination_merges (id INTEGER PRIMARY KEY AUTOINCREMENT, source_nominee_id INTEGER NOT NULL, target_nominee_id INTEGER NOT NULL, submission_ids TEXT NOT NULL, admin_role TEXT, admin_username TEXT, reason TEXT NOT NULL, merged_at TEXT NOT NULL, reversed_at TEXT, reversed_by TEXT, reverse_reason TEXT);
    CREATE TABLE IF NOT EXISTS nomination_shortlists (id INTEGER PRIMARY KEY AUTOINCREMENT, phase_id INTEGER NOT NULL, category_id INTEGER NOT NULL, nominee_id INTEGER NOT NULL, sort_order INTEGER NOT NULL, created_at TEXT NOT NULL, UNIQUE(phase_id,category_id,nominee_id), UNIQUE(phase_id,category_id,sort_order));
    CREATE TABLE IF NOT EXISTS nomination_shortlist_status (phase_id INTEGER NOT NULL, category_id INTEGER NOT NULL, finalized INTEGER NOT NULL DEFAULT 0, finalized_at TEXT, finalized_by TEXT, ready_for_publication INTEGER NOT NULL DEFAULT 0, ready_at TEXT, change_reason TEXT, PRIMARY KEY(phase_id,category_id));
    CREATE TABLE IF NOT EXISTS nomination_settings (
      id INTEGER PRIMARY KEY CHECK(id=1), featured_home INTEGER NOT NULL DEFAULT 1, hidden INTEGER NOT NULL DEFAULT 0, homepage_position TEXT NOT NULL DEFAULT 'after_pulse',
      headline TEXT NOT NULL, supporting_text TEXT NOT NULL, show_countdown INTEGER NOT NULL DEFAULT 1, show_public_total INTEGER NOT NULL DEFAULT 1, self_nomination_allowed INTEGER NOT NULL DEFAULT 0,
      rules_text TEXT NOT NULL, hero_original_token TEXT, hero_webp_token TEXT, hero_avif_token TEXT, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS nomination_audit (id INTEGER PRIMARY KEY AUTOINCREMENT, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, admin_role TEXT, admin_username TEXT, summary TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  `);
  const insertGroup = db.prepare("INSERT OR IGNORE INTO nomination_award_groups(slug,name,sort_order) VALUES(?,?,?)");
  GROUPS.forEach(group => insertGroup.run(group.slug, group.name, group.order));
  const groupRows = Object.fromEntries(db.prepare("SELECT id,slug FROM nomination_award_groups").all().map(row => [row.slug, row.id]));
  const insertCategory = db.prepare(`INSERT OR IGNORE INTO nomination_categories(group_id,slug,name,description,eligibility_instructions,category_type,active,public_nominations,max_finalists,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?)`);
  for (const group of GROUPS) CATEGORY_NAMES[group.slug].forEach((name, index) => {
    const type = name === "Best Friends of the Year" ? "pair" : name === "Best Class of the Year" ? "class" : "individual";
    const isSpecial = name === "Special Recognition Award";
    insertCategory.run(groupRows[group.slug], slugify(name), name, CATEGORY_DESCRIPTIONS[name], group.slug.startsWith("level-") ? `Nominee must be a current ${group.name.replace(" Awards", "")} student.` : "Nominees must meet the published SRC Awards eligibility rules.", type, 1, isSpecial ? 0 : 1, 5, index + 1);
  });
  const updateLegacyDescription = db.prepare("UPDATE nomination_categories SET description=?,updated_at=CURRENT_TIMESTAMP WHERE slug=? AND (trim(description)='' OR description=?)");
  for (const name of Object.values(CATEGORY_NAMES).flat()) {
    const legacyDescription = `Recognising excellence in ${name.replace(/ of the Year$/i, "").toLowerCase()}.`;
    updateLegacyDescription.run(CATEGORY_DESCRIPTIONS[name], slugify(name), legacyDescription);
  }
  db.prepare(`INSERT OR IGNORE INTO nomination_settings(id,headline,supporting_text,rules_text,hero_original_token,hero_webp_token,hero_avif_token) VALUES(1,?,?,?,?,?,?)`).run("SOMEONE DESERVES THE SPOTLIGHT.", "You have seen the work. You know the impact. Now mention the name.", DEFAULT_RULES, options.heroTokens?.original || null, options.heroTokens?.webp || null, options.heroTokens?.avif || null);
  if (!db.prepare("SELECT 1 FROM nomination_phases LIMIT 1").get()) db.prepare("INSERT INTO nomination_phases(title,status,rules_snapshot) VALUES(?,?,?)").run("SRC Awards 2026 Nominations", "draft", DEFAULT_RULES);

  const audit = (admin, action, type, entityId, summary) => db.prepare("INSERT INTO nomination_audit(action,entity_type,entity_id,admin_role,admin_username,summary) VALUES(?,?,?,?,?,?)").run(action, type, String(entityId), admin?.role || null, admin?.username || null, clean(summary, "Audit summary", { max: 500 }));
  const phaseRow = () => db.prepare("SELECT * FROM nomination_phases ORDER BY id DESC LIMIT 1").get();
  function effectivePhase() {
    const phase = phaseRow(); if (!phase) return null;
    const now = nowIso(clock);
    if (phase.status === "scheduled" && phase.opens_at && Date.parse(now) >= Date.parse(phase.opens_at) && (!phase.closes_at || Date.parse(now) < Date.parse(phase.closes_at))) db.prepare("UPDATE nomination_phases SET status='open',updated_at=? WHERE id=?").run(now, phase.id);
    if (["scheduled", "open", "paused"].includes(phase.status) && phase.closes_at && Date.parse(now) >= Date.parse(phase.closes_at)) db.prepare("UPDATE nomination_phases SET status='closed',updated_at=? WHERE id=?").run(now, phase.id);
    return db.prepare("SELECT * FROM nomination_phases WHERE id=?").get(phase.id);
  }
  function settings() { const row = db.prepare("SELECT * FROM nomination_settings WHERE id=1").get(); return { featuredHome: Boolean(row.featured_home), hidden: Boolean(row.hidden), homepagePosition: row.homepage_position, headline: row.headline, supportingText: row.supporting_text, showCountdown: Boolean(row.show_countdown), showPublicTotal: Boolean(row.show_public_total), selfNominationAllowed: Boolean(row.self_nomination_allowed), rules: row.rules_text, hero: { original: row.hero_original_token ? `/api/nominations/files/${row.hero_original_token}` : null, webp: row.hero_webp_token ? `/api/nominations/files/${row.hero_webp_token}` : null, avif: row.hero_avif_token ? `/api/nominations/files/${row.hero_avif_token}` : null } }; }
  function publicData() {
    const phase = effectivePhase(); const site = settings();
    const groups = db.prepare(`SELECT g.slug,g.name,c.id,c.slug categorySlug,c.name categoryName,c.description,c.eligibility_instructions eligibility,c.category_type type FROM nomination_award_groups g JOIN nomination_categories c ON c.group_id=g.id WHERE c.active=1 AND c.public_nominations=1 ORDER BY g.sort_order,c.sort_order`).all();
    const grouped = GROUPS.map(group => ({ slug: group.slug, name: group.name, categories: groups.filter(row => row.slug === group.slug).map(row => ({ id: row.id, slug: row.categorySlug, name: row.categoryName, description: row.description, eligibility: row.eligibility, type: row.type })) }));
    const validTotal = phase ? Number(db.prepare("SELECT COUNT(*) count FROM nomination_submissions WHERE phase_id=? AND status='valid'").get(phase.id).count) : 0;
    return { visible: site.featuredHome && !site.hidden, settings: { headline: site.headline, supportingText: site.supportingText, homepagePosition: site.homepagePosition, showCountdown: site.showCountdown, rules: site.rules, hero: site.hero }, phase: phase ? { status: phase.status, title: phase.title, opensAt: phase.opens_at, closesAt: phase.closes_at, accepting: phase.status === "open" && (!phase.opens_at || Date.parse(nowIso(clock)) >= Date.parse(phase.opens_at)) && (!phase.closes_at || Date.parse(nowIso(clock)) < Date.parse(phase.closes_at)), validTotal: site.showPublicTotal ? validTotal : null } : { status: "draft", accepting: false, validTotal: site.showPublicTotal ? 0 : null }, groups: grouped };
  }
  function candidateInput(category, body) {
    if (category.category_type === "pair") { const first = clean(body.firstPersonName, "First person's name", { required: true, min: 2, max: 140 }), second = clean(body.secondPersonName, "Second person's name", { required: true, min: 2, max: 140 }); if (normalizeName(first) === normalizeName(second)) throw httpError("Best Friends nominations require two different people."); const firstLevel=clean(body.firstPersonLevel,"First person's level",{required:true,min:1,max:60}),firstProgramme=clean(body.firstPersonProgramme,"First person's programme",{required:true,min:2,max:160}),secondLevel=clean(body.secondPersonLevel,"Second person's level",{required:true,min:1,max:60}),secondProgramme=clean(body.secondPersonProgramme,"Second person's programme",{required:true,min:2,max:160});const key = pairKey(first, second); return { type: "pair", name: `${first} & ${second}`, key, level:`${firstLevel} / ${secondLevel}`, programme:`${firstProgramme} / ${secondProgramme}`, phone: normalizeGhanaPhone(body.nomineePhone, false), first, second, details: { firstPersonName: first, firstPersonLevel:firstLevel, firstPersonProgramme:firstProgramme, secondPersonName: second, secondPersonLevel:secondLevel, secondPersonProgramme:secondProgramme } }; }
    const level = clean(body.nomineeLevel || body.level, "Nominee level", { required: true, min: 1, max: 60 });
    const programme = clean(body.nomineeProgramme || body.programme, "Nominee programme or class", { required: true, min: 2, max: 160 });
    if (category.category_type === "class") { const representative = clean(body.classRepresentative, "Class representative", { max: 140 }); const phone = normalizeGhanaPhone(body.nomineePhone, false); return { type: "class", name: `${programme} — ${level}`, key: `class|${normalizeName(level)}|${normalizeName(programme)}`, level, programme, phone, representative, details: { level, programme, classRepresentative: representative } }; }
    const name = clean(body.nomineeName, "Nominee name", { required: true, min: 2, max: 140 }); return { type: "individual", name, key: `person|${normalizeName(name)}|${normalizeName(level)}|${normalizeName(programme)}`, level, programme, phone: normalizeGhanaPhone(body.nomineePhone, false), details: { name, level, programme } };
  }
  function submit(input) {
    const phase = effectivePhase(); if (!phase || phase.status !== "open") throw httpError(phase?.status === "paused" ? "Nominations are temporarily paused." : phase?.status === "closed" ? "This nomination phase is closed." : "Nominations are not open yet.", 409);
    const now = nowIso(clock); if ((phase.opens_at && Date.parse(now) < Date.parse(phase.opens_at)) || (phase.closes_at && Date.parse(now) >= Date.parse(phase.closes_at))) throw httpError("The nomination window is not currently open.", 409);
    const categoryId = numericId(input.categoryId, "category"); const category = db.prepare("SELECT * FROM nomination_categories WHERE id=? AND active=1 AND public_nominations=1").get(categoryId); if (!category) throw httpError("This category is not accepting public nominations.", 404);
    const candidate = candidateInput(category, input); const nominatorName = clean(input.nominatorName, "Nominator name", { required: true, min: 2, max: 140 });
    const nominatorId = normalizeStudentId(input.nominatorStudentId); const nominatorPhone = normalizeGhanaPhone(input.nominatorPhone); const nominatorClass = clean(input.nominatorClass, "Nominator level/programme", { required: true, min: 2, max: 160 });
    if (!bool(input.rulesAccepted)) throw httpError("You must accept the nomination rules and privacy notice.");
    if (!settings().selfNominationAllowed && candidate.type === "individual" && normalizeName(candidate.name) === normalizeName(nominatorName)) throw httpError("Self-nomination is not permitted for this phase.", 409);
    const reason = clean(input.reason, "Reason", { max: 1200 }); const idempotency = clean(input.idempotencyKey, "Submission key", { required: true, min: 16, max: 100 }); if (!/^[A-Za-z0-9_-]{16,100}$/.test(idempotency)) throw httpError("Invalid submission key.");
    try { return transaction(db, () => {
      let nominee = db.prepare("SELECT * FROM nomination_nominees WHERE category_id=? AND normalized_key=? AND merged_into_id IS NULL").get(categoryId, candidate.key);
      if (!nominee) { const result = db.prepare(`INSERT INTO nomination_nominees(category_id,nominee_type,display_name,normalized_key,level,programme,contact_phone,pair_first_name,pair_second_name,class_representative) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(categoryId, candidate.type, candidate.name, candidate.key, candidate.level, candidate.programme, candidate.phone, candidate.first || null, candidate.second || null, candidate.representative || null); nominee = { id: Number(result.lastInsertRowid) }; }
      const publicId = `NOM-${crypto.randomBytes(10).toString("base64url")}`; const correlation = crypto.randomBytes(8).toString("hex");
      db.prepare(`INSERT INTO nomination_submissions(public_id,idempotency_key,phase_id,category_id,nominee_id,submitted_nominee_name,submitted_details,nominee_phone,reason,nominator_name,nominator_student_id,nominator_phone,nominator_class,status,rules_accepted_at,correlation_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'pending_review',?,?,?)`).run(publicId, idempotency, phase.id, categoryId, nominee.id, candidate.name, JSON.stringify(candidate.details), candidate.phone, reason || null, nominatorName, nominatorId, nominatorPhone, nominatorClass, now, correlation, now);
      return { ok: true, reference: publicId, message: "SPOTLIGHT PLACED ✅\n\nYour nomination has been received and will remain sealed until the official nominee reveal. Nominations are not votes, and every submission is subject to eligibility screening." };
    }); } catch (error) { if (String(error.code).includes("SQLITE") && /UNIQUE constraint failed/i.test(String(error.message))) { const prior = db.prepare("SELECT public_id FROM nomination_submissions WHERE idempotency_key=?").get(idempotency); if (prior) return { ok: true, reference: prior.public_id, duplicateReplay: true, message: "This nomination was already received." }; throw httpError("You have already nominated in this category during this phase.", 409); } throw error; }
  }
  function updateSettings(input, admin) { const previous = settings(); const rules = clean(input.rules ?? previous.rules, "Rules", { required: true, min: 20, max: 12000 }); const phase = effectivePhase(); if (["open", "paused", "closed", "archived"].includes(phase.status) && rules !== previous.rules) throw httpError("Material nomination rules are locked after nominations open.", 409); db.prepare(`UPDATE nomination_settings SET featured_home=?,hidden=?,homepage_position=?,headline=?,supporting_text=?,show_countdown=?,show_public_total=?,self_nomination_allowed=?,rules_text=?,updated_at=? WHERE id=1`).run(Number(bool(input.featuredHome)), Number(bool(input.hidden)), choice(input.homepagePosition, PUBLIC_POSITIONS, "homepage position", previous.homepagePosition), clean(input.headline ?? previous.headline, "Headline", { required: true, min: 5, max: 180 }), clean(input.supportingText ?? previous.supportingText, "Supporting text", { required: true, min: 5, max: 500 }), Number(bool(input.showCountdown)), Number(bool(input.showPublicTotal)), Number(bool(input.selfNominationAllowed)), rules, nowIso(clock)); audit(admin, "settings_updated", "settings", 1, "Nomination homepage and privacy settings updated"); return settings(); }
  function setHero(tokens, admin) { const current = db.prepare("SELECT hero_original_token,hero_webp_token,hero_avif_token FROM nomination_settings WHERE id=1").get(); db.prepare("UPDATE nomination_settings SET hero_original_token=?,hero_webp_token=?,hero_avif_token=?,updated_at=? WHERE id=1").run(tokens?.original || null, tokens?.webp || null, tokens?.avif || null, nowIso(clock)); audit(admin, tokens ? "hero_replaced" : "hero_removed", "settings", 1, tokens ? "Nomination hero photograph replaced" : "Nomination hero photograph removed"); return { previous: current, settings: settings() }; }
  function updatePhase(input, admin) { const phase = effectivePhase(); const next = choice(input.status, PHASE_STATUSES, "phase status", phase.status); const transitions = { draft: ["draft","scheduled","open","archived"], scheduled: ["scheduled","draft","open","paused","closed","archived"], open: ["open","paused","closed"], paused: ["paused","open","closed"], closed: ["closed","archived"], archived: ["archived"] }; if (!transitions[phase.status].includes(next)) throw httpError(`Cannot change nomination phase from ${phase.status} to ${next}.`, 409); const opensAt = timestamp(input.opensAt ?? phase.opens_at, "Opening date", ["scheduled","open"].includes(next)); const closesAt = timestamp(input.closesAt ?? phase.closes_at, "Closing date", ["scheduled","open","paused"].includes(next)); if (opensAt && closesAt && Date.parse(closesAt) <= Date.parse(opensAt)) throw httpError("Closing date must be after the opening date."); if (["scheduled","open"].includes(next) && closesAt && Date.parse(closesAt) <= Date.parse(nowIso(clock))) throw httpError("Closing date must be in the future."); const rules = settings().rules; const snapshot=["scheduled","open"].includes(next)?rules:phase.rules_snapshot; db.prepare("UPDATE nomination_phases SET title=?,status=?,opens_at=?,closes_at=?,rules_snapshot=?,updated_at=? WHERE id=?").run(clean(input.title ?? phase.title, "Phase title", { required: true, min: 3, max: 180 }), next, opensAt, closesAt, snapshot, nowIso(clock), phase.id); audit(admin, `phase_${next}`, "phase", phase.id, `Nomination phase changed from ${phase.status} to ${next}`); return dashboard(); }
  function createPhase(input,admin){const current=effectivePhase();if(current&&current.status!=="archived")throw httpError("Archive the current nomination phase before creating another.",409);const title=clean(input.title,"Phase title",{required:true,min:3,max:180});const result=db.prepare("INSERT INTO nomination_phases(title,status,rules_snapshot) VALUES(?,'draft',?)").run(title,settings().rules);audit(admin,"phase_created","phase",result.lastInsertRowid,"New draft nomination phase created");return dashboard();}
  function mapCategory(row) { return { id: row.id, slug: row.slug, name: row.name, groupSlug: row.group_slug, groupName: row.group_name, description: row.description, eligibility: row.eligibility_instructions, type: row.category_type, active: Boolean(row.active), publicNominations: Boolean(row.public_nominations), maxFinalists: row.max_finalists, sortOrder: row.sort_order, locked: Boolean(row.nomination_count) }; }
  function categories() { return db.prepare(`SELECT c.*,g.slug group_slug,g.name group_name,(SELECT COUNT(*) FROM nomination_submissions s WHERE s.category_id=c.id) nomination_count FROM nomination_categories c JOIN nomination_award_groups g ON g.id=c.group_id ORDER BY g.sort_order,c.sort_order`).all().map(mapCategory); }
  function updateCategory(value, input, admin) { const category = db.prepare("SELECT c.*,(SELECT COUNT(*) FROM nomination_submissions s WHERE s.category_id=c.id) nomination_count FROM nomination_categories c WHERE c.id=?").get(numericId(value, "category")); if (!category) throw httpError("Category not found.", 404); if (category.nomination_count && input.slug && input.slug !== category.slug) throw httpError("A category identity cannot change after nominations are received.", 409); const maximum = Number(input.maxFinalists ?? category.max_finalists); if (!Number.isInteger(maximum) || maximum < 1 || maximum > 20) throw httpError("Maximum finalists must be between 1 and 20."); db.prepare(`UPDATE nomination_categories SET description=?,eligibility_instructions=?,active=?,public_nominations=?,max_finalists=?,sort_order=?,updated_at=? WHERE id=?`).run(clean(input.description ?? category.description, "Description", { max: 1000 }), clean(input.eligibility ?? category.eligibility_instructions, "Eligibility", { max: 3000 }), Number(bool(input.active)), Number(bool(input.publicNominations) && category.slug !== "special-recognition-award"), maximum, Math.max(1, Number(input.sortOrder) || category.sort_order), nowIso(clock), category.id); audit(admin, "category_updated", "category", category.id, `${category.name} settings updated`); return categories().find(item => item.id === category.id); }
  function submissionCounts(phaseId) { return db.prepare("SELECT status,COUNT(*) count FROM nomination_submissions WHERE phase_id=? GROUP BY status").all(phaseId); }
  function dashboard() { const phase = effectivePhase(); const counts = Object.fromEntries(submissionCounts(phase.id).map(row => [row.status, Number(row.count)])); const total = Object.values(counts).reduce((a,b)=>a+b,0); return { phase: { id: phase.id, title: phase.title, status: phase.status, opensAt: phase.opens_at, closesAt: phase.closes_at }, settings: settings(), metrics: { total, valid: counts.valid || 0, invalid: counts.invalid || 0, flagged: counts.flagged || 0, uniqueNominators: Number(db.prepare("SELECT COUNT(DISTINCT nominator_student_id) count FROM nomination_submissions WHERE phase_id=?").get(phase.id).count), uniqueNominees: Number(db.prepare("SELECT COUNT(DISTINCT nominee_id) count FROM nomination_submissions WHERE phase_id=?").get(phase.id).count), shortlisted: Number(db.prepare("SELECT COUNT(*) count FROM nomination_shortlists WHERE phase_id=?").get(phase.id).count) }, groups: db.prepare(`SELECT g.slug,g.name,COUNT(s.id) total FROM nomination_award_groups g LEFT JOIN nomination_categories c ON c.group_id=g.id LEFT JOIN nomination_submissions s ON s.category_id=c.id AND s.phase_id=? GROUP BY g.id ORDER BY g.sort_order`).all(phase.id), categoryTotals: db.prepare(`SELECT c.id,c.name,COUNT(s.id) total FROM nomination_categories c LEFT JOIN nomination_submissions s ON s.category_id=c.id AND s.phase_id=? GROUP BY c.id ORDER BY total DESC,c.name`).all(phase.id), recent: db.prepare(`SELECT s.id,s.public_id publicId,s.status,s.created_at createdAt,c.name category,n.display_name nominee FROM nomination_submissions s JOIN nomination_categories c ON c.id=s.category_id JOIN nomination_nominees n ON n.id=s.nominee_id WHERE s.phase_id=? ORDER BY s.id DESC LIMIT 8`).all(phase.id) }; }
  function listSubmissions(query = {}) { const conditions = [], values = []; if (query.categoryId) { conditions.push("s.category_id=?"); values.push(numericId(query.categoryId,"category")); } if (query.status) { conditions.push("s.status=?"); values.push(choice(query.status,SUBMISSION_STATUSES,"submission status")); } if (query.group) { conditions.push("g.slug=?"); values.push(clean(query.group,"award group",{max:40})); } if (query.from) { conditions.push("datetime(s.created_at)>=datetime(?)"); values.push(timestamp(query.from,"From date")); } if (query.to) { conditions.push("datetime(s.created_at)<=datetime(?)"); values.push(timestamp(query.to,"To date")); } if (query.q) { conditions.push("(s.submitted_nominee_name LIKE ? OR s.nominator_student_id LIKE ? OR s.public_id LIKE ?)"); const q=`%${clean(query.q,"Search",{max:100})}%`; values.push(q,q,q); } const where=conditions.length?`WHERE ${conditions.join(" AND ")}`:""; return db.prepare(`SELECT s.id,s.public_id publicId,s.status,s.submitted_nominee_name submittedNomineeName,s.submitted_details submittedDetails,s.nominee_phone nomineePhone,s.reason,s.nominator_name nominatorName,s.nominator_student_id nominatorStudentId,s.nominator_phone nominatorPhone,s.nominator_class nominatorClass,s.invalid_reason invalidReason,s.review_notes reviewNotes,s.created_at createdAt,c.name category,c.id categoryId,g.name groupName,n.id nomineeId,n.display_name canonicalNominee,n.status nomineeStatus FROM nomination_submissions s JOIN nomination_categories c ON c.id=s.category_id JOIN nomination_award_groups g ON g.id=c.group_id JOIN nomination_nominees n ON n.id=s.nominee_id ${where} ORDER BY s.id DESC LIMIT 500`).all(...values).map(row=>({...row,submittedDetails:JSON.parse(row.submittedDetails||"{}")})); }
  function updateSubmissionStatus(value, input, admin) { const id=numericId(value,"submission"), current=db.prepare("SELECT status FROM nomination_submissions WHERE id=?").get(id); if(!current)throw httpError("Submission not found.",404); const status=choice(input.status,SUBMISSION_STATUSES,"submission status"); const reason=clean(input.reason,"Reason",{max:1000}); if(status==="invalid"&&!reason)throw httpError("A written reason is required when invalidating a nomination."); db.prepare("UPDATE nomination_submissions SET status=?,invalid_reason=?,review_notes=?,updated_at=? WHERE id=?").run(status,status==="invalid"?reason:null,clean(input.reviewNotes,"Review notes",{max:3000}),nowIso(clock),id); audit(admin,"submission_status_updated","submission",id,`Submission changed from ${current.status} to ${status}`); return listSubmissions().find(item=>item.id===id); }
  function nomineeRows(query={}) { const conditions=["n.merged_into_id IS NULL"],values=[]; if(query.categoryId){conditions.push("n.category_id=?");values.push(numericId(query.categoryId,"category"));}if(query.status){conditions.push("n.status=?");values.push(choice(query.status,NOMINEE_STATUSES,"nominee status"));}if(query.q){conditions.push("n.display_name LIKE ?");values.push(`%${clean(query.q,"Search",{max:100})}%`);} return db.prepare(`SELECT n.*,c.name category,c.max_finalists maxFinalists,(SELECT COUNT(*) FROM nomination_submissions s WHERE s.nominee_id=n.id AND s.status='valid') valid_count FROM nomination_nominees n JOIN nomination_categories c ON c.id=n.category_id WHERE ${conditions.join(" AND ")} ORDER BY valid_count DESC,n.display_name`).all(...values); }
  function mapNominee(row, all=[]) { const suggestions=all.filter(other=>other.id!==row.id&&other.category_id===row.category_id&&(row.contact_phone&&row.contact_phone===other.contact_phone||similarity(normalizeName(row.display_name),normalizeName(other.display_name))>=.65&&row.level===other.level)).map(other=>({id:other.id,name:other.display_name,validCount:other.valid_count})); return { id:row.id,categoryId:row.category_id,category:row.category,type:row.nominee_type,name:row.display_name,level:row.level,programme:row.programme,phone:row.contact_phone,status:row.status,internalNotes:row.internal_notes,validCount:Number(row.valid_count),duplicateSuggestions:suggestions,verifiedName:row.verified_name,verifiedLevel:row.verified_level,verifiedProgramme:row.verified_programme,verifiedPhone:row.verified_phone,photoUrl:row.photo_token?`/api/nominations/admin/files/${row.photo_token}`:null,photoToken:row.photo_token,publicBio:row.public_bio,campaignStatement:row.campaign_statement,contactStatus:row.contact_status,consentStatus:row.consent_status,consentReceivedAt:row.consent_received_at,ballotOrder:row.ballot_order}; }
  function listNominees(query={}) { const rows=nomineeRows(query); const all=query.categoryId?rows:nomineeRows(); return rows.map(row=>mapNominee(row,all)); }
  function updateNominee(value,input,admin){const id=numericId(value,"nominee"),row=db.prepare("SELECT * FROM nomination_nominees WHERE id=? AND merged_into_id IS NULL").get(id);if(!row)throw httpError("Nominee not found.",404);const status=choice(input.status,NOMINEE_STATUSES,"nominee status",row.status);const allowed={under_review:["under_review","eligible","ineligible","withdrawn"],eligible:["eligible","ineligible","shortlisted","withdrawn"],ineligible:["ineligible","under_review","eligible","withdrawn"],shortlisted:["shortlisted","consent_pending","withdrawn"],consent_pending:["consent_pending","verified","withdrawn"],verified:["verified","ready_for_publication","withdrawn"],ready_for_publication:["ready_for_publication","verified","withdrawn"],withdrawn:["withdrawn","under_review"]};if(!allowed[row.status].includes(status))throw httpError(`Cannot change nominee from ${row.status} to ${status}.`,409);const consentStatus=choice(input.consentStatus,["not_requested","pending","received","declined"],"consent status",row.consent_status);const consentAt=consentStatus==="received"?timestamp(input.consentReceivedAt||nowIso(clock),"Consent date",true):null;db.prepare(`UPDATE nomination_nominees SET status=?,internal_notes=?,verified_name=?,verified_level=?,verified_programme=?,verified_phone=?,public_bio=?,campaign_statement=?,contact_status=?,consent_status=?,consent_received_at=?,ballot_order=?,updated_at=? WHERE id=?`).run(status,clean(input.internalNotes??row.internal_notes,"Internal notes",{max:5000}),clean(input.verifiedName??row.verified_name,"Verified name",{max:140})||null,clean(input.verifiedLevel??row.verified_level,"Verified level",{max:60})||null,clean(input.verifiedProgramme??row.verified_programme,"Verified programme",{max:160})||null,input.verifiedPhone?normalizeGhanaPhone(input.verifiedPhone,false):row.verified_phone,clean(input.publicBio??row.public_bio,"Public biography",{max:3000})||null,clean(input.campaignStatement??row.campaign_statement,"Campaign statement",{max:1200})||null,clean(input.contactStatus??row.contact_status,"Contact status",{max:50}),consentStatus,consentAt,input.ballotOrder==null?row.ballot_order:Math.max(1,Number(input.ballotOrder)||1),nowIso(clock),id);audit(admin,"nominee_updated","nominee",id,`Nominee status updated to ${status}; consent ${consentStatus}`);return listNominees().find(item=>item.id===id);}
  function setNomineePhoto(value,token,admin){const id=numericId(value,"nominee"),row=db.prepare("SELECT photo_token FROM nomination_nominees WHERE id=?").get(id);if(!row)throw httpError("Nominee not found.",404);db.prepare("UPDATE nomination_nominees SET photo_token=?,updated_at=? WHERE id=?").run(token||null,nowIso(clock),id);audit(admin,token?"nominee_photo_updated":"nominee_photo_removed","nominee",id,token?"Approved nominee profile photograph stored":"Nominee photograph removed");return{previous:row.photo_token,nominee:listNominees().find(item=>item.id===id)};}
  function merge(sourceValue,targetValue,reason,admin){const source=numericId(sourceValue,"source nominee"),target=numericId(targetValue,"target nominee");if(source===target)throw httpError("Choose two different nominee records.");const why=clean(reason,"Merge reason",{required:true,min:5,max:1000});return transaction(db,()=>{const rows=db.prepare("SELECT id,category_id FROM nomination_nominees WHERE id IN (?,?) AND merged_into_id IS NULL").all(source,target);if(rows.length!==2||rows[0].category_id!==rows[1].category_id)throw httpError("Nominees must be active records in the same category.",409);const ids=db.prepare("SELECT id FROM nomination_submissions WHERE nominee_id=?").all(source).map(item=>item.id);db.prepare("UPDATE nomination_submissions SET nominee_id=?,updated_at=? WHERE nominee_id=?").run(target,nowIso(clock),source);db.prepare("UPDATE nomination_nominees SET merged_into_id=?,status='withdrawn',updated_at=? WHERE id=?").run(target,nowIso(clock),source);const result=db.prepare("INSERT INTO nomination_merges(source_nominee_id,target_nominee_id,submission_ids,admin_role,admin_username,reason,merged_at) VALUES(?,?,?,?,?,?,?)").run(source,target,JSON.stringify(ids),admin?.role||null,admin?.username||null,why,nowIso(clock));audit(admin,"nominee_merged","nominee",target,`Nominee ${source} merged into ${target}`);return{id:Number(result.lastInsertRowid)};});}
  function unmerge(value,reason,admin){const mergeId=numericId(value,"merge"),why=clean(reason,"Unmerge reason",{required:true,min:5,max:1000});return transaction(db,()=>{const record=db.prepare("SELECT * FROM nomination_merges WHERE id=? AND reversed_at IS NULL").get(mergeId);if(!record)throw httpError("Active merge not found.",404);const ids=JSON.parse(record.submission_ids);const placeholders=ids.map(()=>"?").join(",");if(ids.length)db.prepare(`UPDATE nomination_submissions SET nominee_id=?,updated_at=? WHERE id IN (${placeholders})`).run(record.source_nominee_id,nowIso(clock),...ids);db.prepare("UPDATE nomination_nominees SET merged_into_id=NULL,status='under_review',updated_at=? WHERE id=?").run(nowIso(clock),record.source_nominee_id);db.prepare("UPDATE nomination_merges SET reversed_at=?,reversed_by=?,reverse_reason=? WHERE id=?").run(nowIso(clock),admin?.username||admin?.role||null,why,mergeId);audit(admin,"nominee_unmerged","nominee",record.source_nominee_id,`Merge ${mergeId} reversed`);return{ok:true};});}
  function merges(){return db.prepare(`SELECT m.id,m.source_nominee_id sourceNomineeId,m.target_nominee_id targetNomineeId,s.display_name sourceName,t.display_name targetName,m.reason,m.merged_at mergedAt,m.reversed_at reversedAt,m.reverse_reason reverseReason FROM nomination_merges m JOIN nomination_nominees s ON s.id=m.source_nominee_id JOIN nomination_nominees t ON t.id=m.target_nominee_id ORDER BY m.id DESC LIMIT 200`).all();}
  function shortlist(categoryValue,input,admin){const categoryId=numericId(categoryValue,"category"),phase=effectivePhase(),category=db.prepare("SELECT * FROM nomination_categories WHERE id=?").get(categoryId);if(!category)throw httpError("Category not found.",404);const nomineeIds=[...new Set((input.nomineeIds||[]).map(value=>numericId(value,"nominee")))];if(nomineeIds.length>category.max_finalists)throw httpError(`This category permits at most ${category.max_finalists} finalists.`);const status=db.prepare("SELECT * FROM nomination_shortlist_status WHERE phase_id=? AND category_id=?").get(phase.id,categoryId);if(status?.finalized&&!clean(input.reason,"Change reason",{max:1000}))throw httpError("A written reason is required to change a finalized shortlist.");return transaction(db,()=>{for(const id of nomineeIds){const nominee=db.prepare("SELECT status FROM nomination_nominees WHERE id=? AND category_id=? AND merged_into_id IS NULL").get(id,categoryId);if(!nominee||!["eligible","shortlisted","consent_pending","verified","ready_for_publication"].includes(nominee.status))throw httpError("Only eligible nominees can be shortlisted.",409);}const prior=db.prepare("SELECT nominee_id id FROM nomination_shortlists WHERE phase_id=? AND category_id=?").all(phase.id,categoryId).map(item=>item.id);for(const removed of prior.filter(id=>!nomineeIds.includes(id)))db.prepare("UPDATE nomination_nominees SET status=CASE WHEN status='shortlisted' THEN 'eligible' ELSE status END,ballot_order=NULL,updated_at=? WHERE id=?").run(nowIso(clock),removed);db.prepare("DELETE FROM nomination_shortlists WHERE phase_id=? AND category_id=?").run(phase.id,categoryId);const insert=db.prepare("INSERT INTO nomination_shortlists(phase_id,category_id,nominee_id,sort_order,created_at) VALUES(?,?,?,?,?)");nomineeIds.forEach((id,index)=>{insert.run(phase.id,categoryId,id,index+1,nowIso(clock));db.prepare("UPDATE nomination_nominees SET status=CASE WHEN status='eligible' THEN 'shortlisted' ELSE status END,ballot_order=?,updated_at=? WHERE id=?").run(index+1,nowIso(clock),id);});db.prepare(`INSERT INTO nomination_shortlist_status(phase_id,category_id,finalized,finalized_at,finalized_by,ready_for_publication,change_reason) VALUES(?,?,?,?,?,0,?) ON CONFLICT(phase_id,category_id) DO UPDATE SET finalized=excluded.finalized,finalized_at=excluded.finalized_at,finalized_by=excluded.finalized_by,ready_for_publication=0,change_reason=excluded.change_reason`).run(phase.id,categoryId,Number(bool(input.finalize)),bool(input.finalize)?nowIso(clock):null,bool(input.finalize)?admin?.username||admin?.role:null,clean(input.reason,"Change reason",{max:1000})||null);audit(admin,bool(input.finalize)?"shortlist_finalized":"shortlist_updated","category",categoryId,`${nomineeIds.length} nominees selected${input.reason?`; reason recorded`:""}`);return shortlistDetail(categoryId);});}
  function shortlistDetail(categoryValue){const categoryId=numericId(categoryValue,"category"),phase=effectivePhase();const state=db.prepare("SELECT * FROM nomination_shortlist_status WHERE phase_id=? AND category_id=?").get(phase.id,categoryId)||{finalized:0,ready_for_publication:0};const nominees=db.prepare(`SELECT n.*,c.name category,c.max_finalists maxFinalists,(SELECT COUNT(*) FROM nomination_submissions s WHERE s.nominee_id=n.id AND s.status='valid') valid_count,sl.sort_order FROM nomination_shortlists sl JOIN nomination_nominees n ON n.id=sl.nominee_id JOIN nomination_categories c ON c.id=n.category_id WHERE sl.phase_id=? AND sl.category_id=? ORDER BY sl.sort_order`).all(phase.id,categoryId).map(row=>mapNominee({...row,ballot_order:row.sort_order},[]));return{categoryId,finalized:Boolean(state.finalized),readyForPublication:Boolean(state.ready_for_publication),nominees};}
  function markReady(categoryValue,input,admin){const detail=shortlistDetail(categoryValue);if(!detail.finalized)throw httpError("Finalize the shortlist before preparing publication.",409);const missing=detail.nominees.filter(item=>!item.photoToken||item.consentStatus!=="received"||!item.verifiedName||!item.verifiedLevel||!item.verifiedProgramme||!["verified","ready_for_publication"].includes(item.status));if(missing.length)throw httpError(`${missing.length} shortlisted nominee(s) still need verified status, details, photograph and recorded consent.`,409);if(input.confirm!==true)throw httpError("Explicit confirmation is required.");const phase=effectivePhase();db.prepare("UPDATE nomination_shortlist_status SET ready_for_publication=1,ready_at=? WHERE phase_id=? AND category_id=?").run(nowIso(clock),phase.id,detail.categoryId);for(const item of detail.nominees)db.prepare("UPDATE nomination_nominees SET status='ready_for_publication',updated_at=? WHERE id=?").run(nowIso(clock),item.id);audit(admin,"category_ready_for_publication","category",detail.categoryId,"Private ballot checks completed; public publishing remains disabled");return shortlistDetail(detail.categoryId);}
  function exportCsv(query={}){const rows=listSubmissions(query),header=["Reference","Award group","Category","Submitted nominee","Nominee phone","Reason","Nominator name","Student ID","Nominator phone","Nominator class","Submission status","Nominee status","Submitted at"];return[header,...rows.map(row=>[row.publicId,row.groupName,row.category,row.submittedNomineeName,row.nomineePhone,row.reason,row.nominatorName,row.nominatorStudentId,row.nominatorPhone,row.nominatorClass,row.status,row.nomineeStatus,row.createdAt])].map(row=>row.map(csvCell).join(",")).join("\r\n");}
  function auditHistory(){return db.prepare("SELECT id,action,entity_type entityType,entity_id entityId,admin_role adminRole,admin_username adminUsername,summary,created_at createdAt FROM nomination_audit ORDER BY id DESC LIMIT 300").all();}
  function heroTokens(){const row=db.prepare("SELECT hero_original_token original,hero_webp_token webp,hero_avif_token avif FROM nomination_settings WHERE id=1").get();return new Set(Object.values(row||{}).filter(Boolean));}
  function managedFile(token){return heroTokens().has(token)||Boolean(db.prepare("SELECT 1 FROM nomination_nominees WHERE photo_token=?").get(token));}
  return { publicData,submit,dashboard,settings,updateSettings,setHero,updatePhase,createPhase,categories,updateCategory,listSubmissions,updateSubmissionStatus,listNominees,updateNominee,setNomineePhoto,merge,unmerge,merges,shortlist,shortlistDetail,markReady,exportCsv,auditHistory,managedFile,effectivePhase };
}

module.exports = { createNominationRepository, PHASE_STATUSES, SUBMISSION_STATUSES, NOMINEE_STATUSES, DEFAULT_RULES, normalizeStudentId, normalizeGhanaPhone, pairKey, csvCell, httpError };
